name: 'WechComposite'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello there ${{ inputs.who-to-greet }}. This is in .github
      shell: bash
    - name: use undeclared input
      shell: bash
      run: echo "${{ inputs.environment }}"
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
